coder/enterprise-helm

templates/cemanager.yaml, templates/envproxy.yaml
Reverts "Revert "Rename 'local' envproxy to 'built-in' (#29)"" (lol)
=> Rename 'local' envproxy to 'built-in'

.github/workflows/build.yml, Makefile, scripts/install_deps.sh, scripts/lib.sh
* Add GitHub Workflow that runs when pushing updates to the default
branch, and for pull request events against the default branch
* Add a script to install Helm during the build
* Add a Makefile to run linting with Helm during the build
=> chore: add Helm linting in CI

kube-linter.yaml, templates/timescale.yaml
* Add readiness probe for timescale pod
* Configure delay, timeouts, and thresholds for both readiness and
liveness probes for the timescale pod
=> chore: update timescale readiness and liveness probes

README.md, README.md.gotmpl, values.yaml
- edits to descriptions used in `values.yaml`
- edit, minor reorg to README.md
=> chore: edit Helm chart descriptions

templates/ingress.yaml
=> chore: update ingress-nginx image

templates/rbac.yaml
=> fix: Reduce permissions required for deployment

templates/rbac.yaml
=> fix: Reduce permissions required for deployment (workspace providers)

Chart.yaml
Our current chart is visible here: https://artifacthub.io/packages/helm/coder/coder
Inspired by: https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/Chart.yaml
=> chore: Update chart branding

templates/_common.tpl
=> fix: cemanager accessURL access

templates/NOTES.txt
Since this is being delayed to a patch release
=> remove note about envproxy deprecation

templates/coderd.yaml, templates/dashboard.yaml, templates/environments.yaml, templates/envproxy.yaml, templates/ingress.yaml, templates/psp.yaml, templates/rbac.yaml, templates/timescale.yaml, values.yaml
=> Add replica option to coderd

templates/ingress.yaml
This is the reason the tls isn't working out of the box
=> Fix missing rules on replica ingress

templates/coderd.yaml
coderd was missing DEVURL_HOST environment variables.
=> Add DEVURL_HOST to coderd container

examples/kind/kind.values.yaml, examples/openshift/openshift.values.yaml, templates/NOTES.txt, templates/coderd.yaml, templates/ingress.yaml
=> fix: Remove port 5349 requirement

templates/coderd.yaml, values.yaml
=> feat: allow specifying the super admin password via a secret

Chart.yaml
Reverts cdr/enterprise-helm#133
=> Revert "chore: add minimum Kubernetes version requirement"

scripts/install_deps.sh
* Update kube-linter from 0.2.2 to 0.2.5
* Add gotestsum to summarize test output
* Add golangci-lint to lint test code
=> chore: update dependencies

examples/ingress/ingress.values.yaml, examples/kind/kind.values.yaml, examples/openshift/openshift.values.yaml, kube-linter.yaml
* Update OpenShift example to create Route with Ingress object
* Remove superfluous configuration options
* Enable lint check for resource request/limit settings
=> chore: clean up examples

.github/workflows/build.yml
* Update 1.22 from 1.22.2 to 1.22.4
* Add 1.23.0
=> chore: update versions of kindest/node

templates/_common.tpl, templates/coderd.yaml, templates/ingress.yaml, templates/networkpolicies.yaml, templates/psp.yaml, templates/rbac.yaml, templates/timescale.yaml, tests/defaults_test.go, tests/deployment_test.go
Add the Standard Labels that Helm describes in its best practices
documentation: https://helm.sh/docs/chart_best_practices/labels/
=> feat: add recommended labels for all objects
