coder/enterprise-helm

templates/_envproxy.tpl

Now that the kprovider is used on envproxy it needs the same kube permissions for getting resources as cemanager

Add parity to kube resources on envproxy

---

templates/_common.tpl
templates/cemanager.yaml
templates/envproxy.yaml

This enables communication between envproxy and cemanager, which will soon be the only way for envproxy to handle authenticating requests. Right now we generate a shared user and key secret between both services, this will probably change in the future but works for now.

Add cemanager url and creds env vars for envproxy detachment

---

templates/_environments.tpl

1. Helm chart stores pod tolerations in `tolerations` key inside the environments config map.
2. Opening `kprovider` client requires the kube api-server to get the config map.
That's because the config map name is required to parse out the pod tolerations.
1. Helm chart stores pod tolerations JSON in `POD_TOLERATIONS` environment variable.
2. If `POD_TOLERATIONS` env var is set, ce-manager parses them out of the environment into new `v1.PodToleration` kube objects.
1. Removes reliance on kube apiserver
2. Removes reliance on config map
3. Cleaner code
4. Faster performance
This PR should be reviewed in conjunction with cdr/c [6206](https://github.com/cdr/c/pull/6206)

inject pod tolerations as JSON string for new POD_TOLERATIONS env var

---

templates/_cemanager.tpl
templates/_envproxy.tpl
templates/ingress.yaml

Enables the `kprovider` to manage storage class resources  as part of a greater effort to prevent environment volume resizes when the storage class for said environment does not allow volume expansion. See [6351](https://github.com/cdr/m/pull/6351).

add storage class permissions

---

templates/cemanager.yaml

Failed to see this due to a bug where the init container was exiting with 0 after failing.

fix: pass namespace env into migrations init container and wait for pg

---

templates/cemanager.yaml
templates/dashboard.yaml
templates/envproxy.yaml

Now that we don't have to account for migrations while the probes are
running, we're free to set these back to reasonable times so it doesn't
take ages for cemanager/envproxy to be detected as ready.

fix: change readiness/liveness probes to reasonable intervals

---

templates/cemanager.yaml
templates/envproxy.yaml

This will recreate the token secret, but it should be fine since we auto-migrate on startup of cemanager, and the old one will be cleaned up from helm. woohoo

Rename 'local' envproxy to 'built-in'

---

templates/cemanager.yaml
templates/envproxy.yaml

This reverts commit cffdd9c3b4929dd5f55f9acf4b8af8cff7addeae.
We can't update the helm submodule until https://github.com/cdr/m/pull/7353 gets in and there are updates in the helm chart I would like to rely on

Revert "Rename 'local' envproxy to 'built-in' (#29)"

---

.github/dependabot.yml

This configures dependabot to scan our GitHub Actions Workflows
and open a Pull Request whenever new versions of the Actions
we use (e.g. styfle/cancel-workflow-action) are available.

chore: use dependabot to track GitHub Actions

---

.github/workflows/build.yml
.helmignore
kube-linter.yaml
scripts/test_helm.sh

* Suppress current failures by excluding them in kube-linter config
* Change GitHub Actions build to enforce lint failures

chore: enforce kube-linter errors

---

templates/timescale.yaml

* Change the hook to run "pg_ctl stop" without su, which already
runs as the postgres user, since that's the Pod's runAsUser
* Explicitly define a terminationGracePeriodSeconds setting, set
to 120 seconds, rather than relying on the default (30 seconds)
This should stop the postgres database pod more quickly, while also doing so more safely than before.
I installed this chart into my namespace on dev-2, used the following command to scale the StatefulSet up/down as needed:
```shell-session
kubectl scale statefulsets timescale --namespace coder-jawnsy-m --replicas 1
```
I then used the following command to watch for events:
```shell-session
kubectl get events --namespace=coder-jawnsy-m --watch
```
Here's the output using the Helm chart from master during container stop:
```
0s …
```

fix: run pre-stop hook without su

---

templates/timescale.yaml

Add a coder.deployment label to be consistent with other components,
to simplify our ce-diagnostics script.
I used `make deploy` and then verified that the label appears on the timescale-0 pod:
```shell-session
[coder@jawnsy-m enterprise-helm]$ kubectl describe pod timescale-0
Name:         timescale-0
Namespace:    coder-jawnsy-m
Priority:     0
Node:         gke-dev-2-default-pool-cba3c583-0qyu/10.1.0.62
Start Time:   Thu, 18 Mar 2021 01:00:35 +0000
Labels:       app=timescale
coder.deployment=postgresql
controller-revision-hash=timescale-994689566
statefulset.kubernetes.io/pod-name=timescale-0
Annotations:  cni.projectcalico.org/podIP: 10.8.3.226/32
```

chore: add coder.deployment label for PostgreSQL

---

templates/timescale.yaml

* Use a read-only root filesystem and provide emptyDir volumes for
paths that PostgreSQL needs to write at runtime
* Drop privileges and prevent privilege escalation in the container
I tested this manually as follows:
1. Copied the template into the monorepo deploy/helm submodule directory, disabling the post-install/post-checkout hooks to avoid the submodule from being overwritten
2. Verify that `make deploy` was successful
3. Checked that the pod was running
4. Checked that the rootfs is mounted ro
5. Ran the image locally using docker and checked the output of `docker diff`
```shell-session
[coder@jawnsy-m deploy]$ make deploy
Successfully packaged chart and saved it to: build/helm/pkg/coder-1.17.0-rc.2+65-g43b30c5ce-dirty.76969c3319-20210319.tgz
Release "coder" has been upgraded. …
```

chore: security hardening for timescale image

---

templates/envproxy.yaml

* Use a read-only root filesystem
* Drop privileges and prevent privilege escalation in the container
I tested by running `make deploy` and verifying that envproxy is running and looks OK. I also verified that the mounts are mostly read-only.
```shell-session
[coder@jawnsy-m deploy]$ make deploy
Successfully packaged chart and saved it to: build/helm/pkg/coder-1.17.0-rc.2+65-g43b30c5ce-dirty.76969c3319-20210319.tgz
Release "coder" has been upgraded. Happy Helming!
NAME: coder
LAST DEPLOYED: Sun Mar 21 20:09:38 2021
NAMESPACE: coder-jawnsy-m
STATUS: deployed
REVISION: 6
TEST SUITE: None
[coder@jawnsy-m deploy]$ kubectl get pods
NAME                                        READY   STATUS    RESTARTS   AGE
cemanager-7899fff459-cd55q                  1/1     Running   0          41m …
```

chore: security hardening for envproxy image

---

README.md
README.md.gotmpl
templates/cemanager.yaml

We rebranded the product from Coder Enterprise to Coder; this change
updates the text accordingly. Some references (such as URLs and
variable names) have not been changed.

chore: rename instances of Coder Enterprise to Coder

---

templates/_common.tpl

I originally didn't know where this was coming from, and thought that we just had the data in the DB from 1.16 previously, but when digging around I saw that we still hard code the `/proxy` path for built-in WSPs. This will set it to just the hostname and will apply on deployment.

Remove hardcoded /proxy path from built-in wsp

---

templates/cemanager.yaml
templates/ingress.yaml

This is behind a deployment feature flag, so will not provide any security concerns.

feat: Expose ports for WebRTC TURN server 

---

templates/cemanager.yaml

Don't even want a chance of regression by customers not having a secret or something.

fix: Only mount certificates if p2p is enabled

---

templates/ingress.yaml

changing ingress `externalTrafficPolicy` value from `Local` to `Cluster`, as it fixes the issue with AWS ELB not forwarding traffic to a node that has the nginx ingress instance running, as documented [here](https://app.clubhouse.io/coder/story/9632/eks-load-balancer-is-running-but-status-says-it-s-out-of-service-and-doesn-t-route-traffic).
a customer found this solution from this [GitLab issue](https://gitlab.com/gitlab-org/charts/gitlab/-/issues/939). only issue is that it's making the IP addresses of the routed traffic private, which removes the ability for our audit logs to properly identify people.
submitting this PR to open up the discussion.

update ingress external traffic policy

---

README.md
templates/ingress.yaml
values.yaml

Allows configuring two new variables
`ingress.service.externalTrafficPolicy`: It was found that setting this to `Local` causes issues in EKS, and it was changed to `Cluster` in https://github.com/cdr/enterprise-helm/pull/63. This changes the default back to `Local` since this is the most sensible default, and makes it configurable.
`ingress.deployment.kind`: In deployments that use `externalTrafficPolicy: Cluster`, the user's IP becomes masked by kube-proxy. This allows ingress-nginx to be deployed as a `DaemonSet` to prevent this.

feat: configurable ingress externalTrafficPolicy and deploy kind

---

templates/cemanager.yaml

This fixes cloud_sql_proxy in iam mode never being detected as ready.

fix: pass correct sslmode to pg_isready

---

README.md
examples/images.yaml
templates/cemanager.yaml
values.yaml

We should be cautious merging this. We'll need to document the removal of envbuilder, as I'd assume helm will throw an error if a customer keeps this value.

chore: Remove envbuilder

---

README.md
kube-linter.yaml
templates/cemanager.yaml
templates/envproxy.yaml
values.yaml

This PR makes the `readOnlyRootFilesystem` field configurable via the `values.yaml`. It is enabled by default.

Make readOnlyRootFilesystem configurable

---

templates/cemanager.yaml

Helm updates to support https://github.com/cdr/m/pull/8248

feat: expose port 8443 on ce-manager for https

---

.github/workflows/build.yml

Rename master to main in the GitHub Actions workflow.

ci: rename master branch to main

---

README.md
examples/images.yaml
examples/kind/kind.values.yaml
templates/dashboard.yaml
templates/ingress.yaml
values.yaml

We aren't deprecating the dashboard until next release, so for now we can use a cemanager replica to essentially perform the same function.

chore: Add dashboard image back with cemanager replica

---

NOTES.txt
README.md
README.md.gotmpl
templates/NOTES.txt

Notes were never actually outputted before... now customers can detect deprecation notices when upgrading!
Run the following to test it out yourself:
```shell-session
$ helm install --dry-run --debug coder ./
```

fix: Move notes to templates/notes

---

README.md
README.md.gotmpl
examples/images.yaml
examples/kind/kind.values.yaml
templates/NOTES.txt
templates/_common.tpl
templates/coderd.yaml
templates/dashboard.yaml
templates/envproxy.yaml
templates/ingress.yaml
templates/psp.yaml
values.yaml

Enables migration from `cemanager` to `coderd` in values.yaml.
Deployments will output a deprecation notice to update the value.
Output when updating to 1.20 with built-in ingress:
Output when updating to 1.20 with custom ingress:
Allows customers to remove envproxy and the dashboard in 1.20, without a forced removal.

chore: Migrate cemanager to coderd

---

kube-linter.yaml
templates/ingress.yaml
values.yaml

Replace the use of deprecated apiVersions with the corresponding
stable versions.
--
Tested this manually in the latest monorepo.

feat: remove deprecated v1beta APIs

---

templates/coderd.yaml
templates/dashboard.yaml
templates/envproxy.yaml

Remove the runAsUser setting so that we run as the default image
USER (coder, uid 1000) in unrestricted Kubernetes environments.
In restricted security environments, such as OpenShift with the
restricted Security Context Constraint, we will run as the uid
for the namespace.
This also applies additional security constraints, preventing
privilege escalation for the migration container and running
as a non-root user.
---
I tested this in GKE and OpenShift with the default `restricted` SCC:
```
22:33 coder@jawnsy-m ~/projects/enterprise-helm $ kubectl exec -it dashboard-85bdd59bd5-b7cpz -- id
uid=1000630000(1000630000) gid=0(root) groups=0(root),1000630000
```

feat: remove runAsUser and add runAsNonRoot

---

templates/NOTES.txt
templates/_common.tpl
templates/_migrate.tpl

If an old value is specified, migrations will now prefer that.
This bug was found with the deprecated value `postgres.useDefault=false`... since the new one was technically set with `postgres.default.enable=true`, it skipped the fallback.

fix: Migrations prefer old value over new

---

templates/_migrate.tpl

Fixes a bug where old values are used even if they aren't set.

fix: Ensure old value is set before applying

---

templates/coderd.yaml

This change results in coderd waiting for PostgreSQL to become
available, rather than using pg_isready to do the same. This will
allow us to remove postgresql from the coderd container.
---
I tested this by scaling down the timescale statefulset and coderd deployment, scaling up coderd, waiting the logs for the migrations container, and starting up the timescale pod -- as expected, the coderd command re-connects to the database every 3 seconds until it succeeds:
```
2021-07-12 16:12:45.986 [ERROR] (migrate)       <global_flags.go:115>   open database   {"pqurl": "postgresql://coder@timescale.coder-jawnsy-m.svc.cluster.local:5432/coder?sslmode=disable\u0026timezone=UTC"} ...
"error": connect to postgres:
coder.com/m/product/coder/pkg/database.Open …
```

feat: wait for postgres availability in Go

---

README.md
examples/openshift/openshift.values.yaml
kube-linter.yaml
scripts/test_helm.sh
templates/coderd.yaml
values.yaml

I tested this in dev-3, seems to work fine. I haven't touched the other containers, since we're phasing them out anyways.
More info about seccomp: https://kubernetes.io/docs/tutorials/clusters/seccomp/
The default option isn't very restrictive, but is better than nothing and suitable for most applications.

feat: configurable pod and container security contexts

---

templates/_common.tpl
templates/_migrate.tpl
templates/coderd.yaml

This was omitted when transitioning to the simplified coderd Helm to begin testing as soon as possible.
coderd supports splitting by `:` to load certificates from path.

fix: Add DevURL TLS secret to SSL_SERVER_*

---

values.yaml

This was removed to simplify the Helm. Customers use it, and we can always deprecate it later.

chore: Add back certs.*

---

README.md
templates/coderd.yaml
values.yaml

Add coderd.trustProxyIP helm value

---

Chart.yaml

Enforce the minimum Kubernetes version in Helm chart, according
to our version support policy.
--
When using an older version of Kubernetes, the error will look like this:
```shell-session
$ helm template --kube-version=1.18.1 coder .
Error: chart requires kubeVersion: >= 1.19.0 which is incompatible with Kubernetes v1.18.1
```
Also verified with `kind`:
```shell-session
$ kubectl get node
NAME                  STATUS   ROLES    AGE   VERSION
coder-control-plane   Ready    master   52s   v1.18.2
$ helm install coder . --namespace=coder
Error: chart requires kubeVersion: >= 1.19.0 which is incompatible with Kubernetes v1.18.2
```

chore: add minimum Kubernetes version requirement

---

templates/coderd.yaml

This caused the migration to always have empty data

Add tolerations and nodeSelector env vars to init container

---

templates/coderd.yaml
templates/timescale.yaml

Cilium seems to check this label when identifying services

chore: set app label in coderd deployment

---

templates/coderd.yaml
values.yaml

If TLS is terminated by an ALB, the service port 80 routes traffic without redirecting
to HTTPS and the HTTPS port presents an error since it's pointing to another HTTPS
port of the node.
This change allows the load balancer to expose only port 443 externally which routes to
the HTTP port of the coderd pod.

Load balancer TLS termination

---

templates/coderd.yaml
values.yaml

This reverts commit be5b7f6e8872517d24eda0fffdc1373a7e3bc78e.
--
Reverted this because it broke dogfood despite no changes being made to the example values files. This means that this change was not backward-compatible.

revert: "Load balancer TLS termination (#144)"

---

examples/ingress/ingress.values.yaml
templates/ingress.yaml

I'm using the following command to ensure the right objects are being created: 
`helm template coder . -f examples/ingress/ingress.values.yaml --set postgres.default.enable=false`
The goal of this is to:

add example for custom ingress

---

templates/networkpolicies.yaml

This will prevent ingress traffic for all workspace pods (already done by coderd on workspace start, but requires creation and cleanup of a network policy) via a policy defined in the Helm chart. In the future, this will make it possible to customize the ingress traffic if desired.
New policy:
```shell-session
$ kubectl describe networkpolicy ingress-deny-all
Name:         ingress-deny-all
Namespace:    coder-jawnsy-m
Created on:   2021-09-01 00:04:33 +0000 UTC
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: coder
meta.helm.sh/release-namespace: coder-jawnsy-m
Spec:
PodSelector:     com.coder.resource=true
Allowing ingress traffic:
<none> (Selected pods are isolated for ingress connectivity)
Not affecting egress traffic
Policy Types: Ingress
``` …

feat: add network policy for workspaces

---

scripts/package.sh
scripts/test_helm.sh

Lint all subdirectories under examples automatically. This has the
effect of linting the ingress example, in addition to the existing
kind and openshift examples.

chore: lint all examples, including ingress

---

tests/security_context_test.go

This PR adds an additional `PodSecurityContext` test for the kind example.
(thank you @jawnsy for the guidance ♥️)

feat: add security context test for kind example

---

templates/ingress.yaml

Devurls will now support suffixs, this strips that suffix and places `*.domain`.
The `*.domain` will include the suffix for the DNS, but the Go code needs to read the suffix.
Example:
Input: `*-prod.example.com`
Output: `*.example.com`
Should I implement some sort of regex check to test the suffix is valid DNS characters and fail if they do something wonky? I'd like to add some basic validation, but don't want to break old deployments.

feat: Strip devurl suffixs from input for host

---

tests/defaults_test.go
tests/values.go

Add a test to ensure that all objects are created in the
designated release namespace.

chore: enforce consistent namespace

---

templates/coderd.yaml

The entrypoint script previously set environment variables as
flags to coderd. coderd now consumes the environment variables
directly, removing the need for the script.
There were a few variables that didn't match up, and I'll be creating
a PR to fix those.

cleanup: Execute coderd directly

---

kube-linter.yaml
templates/coderd.yaml
templates/timescale.yaml

Add the default update strategy settings, as these are checked
by the kube-linter linter. This is not a behavior change, and
simply encodes the default settings into our Chart.

chore: add update strategy configuration

---

examples/ingress/ingress.values.yaml
examples/kind/kind.values.yaml
examples/openshift/openshift.values.yaml
tests/examples_test.go
tests/utils.go

When using ClusterIP services, such as for Ingress objects, the
LoadBalancer-specific externalTrafficPolicy setting must not be
set, so explicitly unset it for those examples.

fix: unset service externalTrafficPolicy in examples

---

.github/workflows/build.yml
.github/workflows/fuzz.yaml

Due to a typo (github.event_type rather than github.event_name),
the cancel previous runs workflow action was not running.

chore: fix cancel workflow action

---

tests/values.go

By default, copier performs a shallow copy, though this was not
documented very clearly. The consequence is that running tests in
parallel is racy.
This fixes the code to perform a deep copy (as originally intended)
so that parallel tests run correctly.

chore: use a deep instead of shallow copy of values

---

.gitignore
templates/networkpolicies.yaml
tests/network_policy_test.go

Turns out that istio doesn't like the new network policy rules.
Instead of adding rules to specifically work with every service mesh out there, just allow all egress traffic from coderd and timescale.

fix(helm): allow istio traffic in network policies

---

.github/workflows/build.yml
.github/workflows/fuzz.yaml

Use GitHub's concurrency feature to cancel in-progress builds
on pull request events, and serialize builds for branch push
events.

chore: enforce concurrency with GitHub feature

---

templates/NOTES.txt
tests/values.go

If trustProxyIP is set, emit a warning notifying the user that
this setting is deprecated and replaced by the reverseProxy
settings.
---
Tested this using: `$ helm install coder . --dry-run --set coderd.trustProxyIP=true`
Emits the following output:
```
NOTES:
======================= DEPRECATION NOTICE =======================
WARNING: The coderd "trustProxyIP" setting is deprecated. Instead,
use the coderd "reverseProxy" setting to configure trusted headers
and origins.
See https://coder.com/docs/coder/latest/guides/deployments/proxy
======================= DEPRECATION NOTICE =======================
```

chore: add note indicating trustProxyIP is deprecated

---

templates/legacy.tpl

When using deprecated values, emit an error since those values no
longer have an effect.
---
Emits errors like the following
```
$ helm install coder . --dry-run --set=ingress.tls.hostSecretName="abc"
Error: INSTALLATION FAILED: execution error at (coder/templates/legacy.tpl:22:4): The 'ingress.tls.hostSecretName' setting was was removed in 1.27; use 'coderd.tls.hostSecretName' instead
```

feat: fail when using deprecated values

---

Chart.yaml
templates/NOTES.txt
tests/defaults_test.go
tests/examples_test.go
tests/notes_test.go
tests/values.go

* Relax version constraint to allow installation on Kubernetes
1.19 or later, with a warning message for unsupported versions
(prior to 1.21)
* Set chart and app version to 1.28.0

feat: permit installation on Kubernetes >= 1.19

---

templates/ingress.yaml
templates/legacy.tpl

changed the ingress template to point to the coderd TLS values, resulting in deprecation of the `ingress.tls.hostSecretName` and `ingress.tls.devurlsHostSecretName` values.

fix: update ingress template TLS values

---

README.md
values.yaml

simple change to the `loadBalancerIP` documentation. this value is applicable to both `Ingress` & `LoadBalancer` Service types, and can be used for both internal/external IPs.

chore: update LB IP docs

---

templates/networkpolicies.yaml
tests/network_policy_test.go

This fixes TURN for larger-scale deployments which require
high-availability.

fix: Allow UDP traffic between coderd pods for TURN

---

templates/rbac.yaml

fixes the below error, which was caused by  #255, which re-named the `environments` service account to `workspaces`
```
create workspace: get user info from image: create image pod: pods "image-" is forbidden: error looking up service account coder/environments: serviceaccount "environments" not found
```

fix: service account naming

---

README.md
templates/coderd.yaml
tests/values.go
values.yaml

a customer asked if we could filter out the `DEBUG` logging in `coderd`, as they're ingesting the logs into DataDog, and the frequency of which is driving up costs.
creates a `true/false` value for the `VERBOSE` environment variable in the `coderd` container.
closes [this issue](https://github.com/coder/v1/issues/12944).

feat: toggle verbose logging

---

templates/coderd.yaml

This should prevent clients from being load balanced accross many coderd instances, which ideally results in fewer workspace connections.

fix: Add `sessionAffinity` to the coderd Service

---

templates/coderd.yaml

```
Warning  SyncLoadBalancerFailed  96s (x6 over 4m11s)  service-controller  Error syncing load balancer: failed to ensure load balancer: unsupported load balancer affinity: ClientIP
```
Folks can still set it in `serviceSpec` if they need to.

Revert #267 as it does not play nice with AWS ELB

---

templates/rbac.yaml
tests/rbac_test.go
tests/utils.go

this PR builds on the work done in #252 and the feedback in #269. I'm leaving this in a draft state as we work to identify & remove unnecessary permissions.
ideally this should slim down the role to only the bare minimum permissions, as to enable smoother installs on OpenShift and any K8s distro.

refactor: generalize & slim down role permissions

---

README.md
templates/_common.tpl
tests/postgres_test.go
tests/values.go
values.yaml

Helm change for https://github.com/coder/v1/pull/13216

feat: Allow specifying non-public schema for database
